// import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from '@next/font/google';
import { useContext, useEffect, useState } from 'react';
import BigPicCarousel from '../components/big-pic-carousel';
import Layout from '../components/layout';
import SearchBox from '../components/searchbox';
import Section from '../components/section';
import SmallPicCarousel from '../components/small-pic-carousel';
import TextCarousel from '../components/text-carrousel';
import Context from '../context';
import prisma from './../lib/prisma';

// const inter = Inter({ subsets: ['latin'] });

export default function Home({ user }) {
  const { dispatch } = useContext(Context);
  const [homeData, setHomeData] = useState();

  useEffect(() => {
    dispatch({ type: 'SET_USER', payload: user[0] });
  }, [user, dispatch]);

  // useEffect(() => {
  //   const fetchHomeData = async () => {
  //     const res = await fetch('/api/home');
  //     const json = await res.json();
  //     setHomeData(json);
  //   };

  //   fetchHomeData();
  // }, []);

  const headerSettings = {
    showLeft: false,
    showCenter: true,
    showRight: true,
    showLogout: false,
  };

  return (
    <Layout headerSettings={headerSettings}>
      <SearchBox />
      <TextCarousel />
      <BigPicCarousel list={homeData?.categoryList} />
      <Section title="Most Popular">
        <SmallPicCarousel list={homeData?.mostPopular} />
      </Section>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const user = await prisma.user.findMany({
    where: { id: 'cldv2kak0000029d1k3qygxic' },
  });
  return {
    props: { user },
    revalidate: 10,
  };
};

// return (
//   <>
//     <Head>
//       <title>Create Next App</title>
//       <meta name="description" content="Generated by create next app" />
//       <meta name="viewport" content="width=device-width, initial-scale=1" />
//       <link rel="icon" href="/favicon.ico" />
//     </Head>
//     <main className={styles.main}>
//       <div className={styles.description}>
//         <p>
//           Get started by editing&nbsp;
//           <code className={styles.code}>pages/index.js</code>
//         </p>
//         <div>
//           <a
//             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             By{' '}
//             <Image
//               src="/vercel.svg"
//               alt="Vercel Logo"
//               className={styles.vercelLogo}
//               width={100}
//               height={24}
//             />
//           </a>
//         </div>
//       </div>

//       <div className={styles.center}>
//         <Image
//           className={styles.logo}
//           src="/next.svg"
//           alt="Next.js Logo"
//           width={180}
//           height={37}
//         />
//         <div className={styles.thirteen}>
//           <Image
//             src="/thirteen.svg"
//             alt="13"
//             width={40}
//             height={31}
//           />
//         </div>
//       </div>

//       <div className={styles.grid}>
//         <a
//           href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           className={styles.card}
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={inter.className}>
//             Docs <span>-&gt;</span>
//           </h2>
//           <p className={inter.className}>
//             Find in-depth information about Next.js features and&nbsp;API.
//           </p>
//         </a>

//         <a
//           href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           className={styles.card}
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={inter.className}>
//             Learn <span>-&gt;</span>
//           </h2>
//           <p className={inter.className}>
//             Learn about Next.js in an interactive course with&nbsp;quizzes!
//           </p>
//         </a>

//         <a
//           href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           className={styles.card}
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={inter.className}>
//             Templates <span>-&gt;</span>
//           </h2>
//           <p className={inter.className}>
//             Discover and deploy boilerplate example Next.js&nbsp;projects.
//           </p>
//         </a>

//         <a
//           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           className={styles.card}
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={inter.className}>
//             Deploy <span>-&gt;</span>
//           </h2>
//           <p className={inter.className}>
//             Instantly deploy your Next.js site to a shareable URL
//             with&nbsp;Vercel.
//           </p>
//         </a>
//       </div>
//     </main>
//   </>
// )
